version: '3.8'

services:
  grupo_sbf_db:
    container_name: mysql_container
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=grupo_sbf
    ports:
      - "3306:3306"
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      - app-network

  grupo_sbf_app:
    container_name: app_container
    image: node:16
    restart: unless-stopped
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - grupo_sbf_db
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    networks:
      - app-network
    volumes:
      - "./:/app"

networks:
  app-network:
    driver: bridge

volumes:
  mysql-volume:
